'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button'; import { Checkbox } from '@/components/ui/checkbox'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Textarea } from '@/components/ui/textarea';
import { trackSubmitApplication } from '@/lib/analytics/meta-pixel';
export function PilotApplicationForm(){const [status,setStatus]=useState('');const [loading,setLoading]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setStatus('');const f=new FormData(e.currentTarget);const body={fullName:f.get('fullName'),companyName:f.get('companyName'),email:f.get('email'),phone:f.get('phone'),businessSegment:f.get('businessSegment'),approximateContacts:f.get('approximateContacts'),mainChallenge:f.get('mainChallenge'),privacyAccepted:f.get('privacyAccepted')==='on',pilotTermsAccepted:f.get('pilotTermsAccepted')==='on',website:f.get('website')};try{const res=await fetch('/api/pilot-applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const json=await res.json();setStatus(json.message||json.error||'Não foi possível enviar.');if(res.ok){if(json.accepted===true)trackSubmitApplication();e.currentTarget.reset();}}catch{setStatus('Não foi possível enviar. Verifique sua conexão.');}finally{setLoading(false)}}return <form id="solicitar" onSubmit={submit} className="border-border bg-card mx-auto mt-12 max-w-3xl rounded-3xl border p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-semibold">Solicitar acesso ao piloto</h2><p className="text-muted-foreground mt-2">As vagas são analisadas e o envio não libera acesso automaticamente.</p><div className="mt-6 grid gap-5 sm:grid-cols-2">
{[['fullName','Nome completo','text',true],['companyName','Empresa','text',false],['email','E-mail','email',true],['phone','WhatsApp','tel',false],['businessSegment','Segmento','text',true],['approximateContacts','Quantidade aproximada de contatos','text',true]].map(([id,label,type,required])=><div key={String(id)}><Label htmlFor={String(id)}>{label}</Label><Input className="mt-2" id={String(id)} name={String(id)} type={String(type)} required={Boolean(required)} maxLength={254}/></div>)}
</div><div className="mt-5"><Label htmlFor="mainChallenge">Principal dificuldade comercial</Label><Textarea className="mt-2 min-h-28" id="mainChallenge" name="mainChallenge" required minLength={10} maxLength={1500}/></div><div className="sr-only" aria-hidden="true"><Label htmlFor="website">Site</Label><Input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>
<div className="mt-6 space-y-4"><label className="flex items-start gap-3 text-sm"><Checkbox name="privacyAccepted" required/><span>Li e aceito a <Link className="text-primary underline" href="/politica-de-privacidade" target="_blank" rel="noopener noreferrer">Política de Privacidade</Link>.</span></label><label className="flex items-start gap-3 text-sm"><Checkbox name="pilotTermsAccepted" required/><span>Entendo e aceito as regras do <Link className="text-primary underline" href="/programa-piloto" target="_blank" rel="noopener noreferrer">Programa Piloto</Link>.</span></label></div>
<Button disabled={loading} className="mt-7 w-full" type="submit">{loading?'Enviando...':'Enviar solicitação'}</Button>{status?<p role="status" className="mt-4 text-sm">{status}</p>:null}</form>}
