'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { BarChart3,BriefcaseBusiness,CircleDollarSign,ContactRound,Target,Trophy,TrendingDown,Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useAuth } from '@/hooks/use-auth';
import { formatCurrency } from '@/lib/currency';
import { normalizeError } from '@/lib/errors/normalize-error';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { SkeletonCard } from '@/components/dashboard/skeleton';

type Period='7'|'30'|'month'|'90';
type ContactRow={created_at:string}; type DealRow={status:string;value:number|null;stage_id:string;created_at:string}; type StageRow={id:string;name:string;position:number;color:string};
type Report={totalContacts:number;newContacts:number;open:number;won:number;lost:number;pipelineValue:number;conversion:number;average:number;contactsByDay:{label:string;value:number}[];stages:{name:string;count:number;value:number;color:string}[]};
function periodStart(period:Period){const now=new Date();if(period==='month')return new Date(now.getFullYear(),now.getMonth(),1);const date=new Date(now);date.setDate(now.getDate()-Number(period)+1);date.setHours(0,0,0,0);return date;}
const percent=new Intl.NumberFormat('pt-BR',{style:'percent',maximumFractionDigits:1});

export default function ReportsPage(){const {accountId,profileLoading,defaultCurrency}=useAuth();const [period,setPeriod]=useState<Period>('30');const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
const load=useCallback(async()=>{if(!accountId)return;setLoading(true);setError(null);try{const db=createClient(),start=periodStart(period).toISOString();const [total,contacts,deals,stages]=await Promise.all([db.from('contacts').select('id',{count:'exact',head:true}).eq('account_id',accountId),db.from('contacts').select('created_at').eq('account_id',accountId).gte('created_at',start).order('created_at'),db.from('deals').select('status,value,stage_id,created_at').eq('account_id',accountId).gte('created_at',start),db.from('pipeline_stages').select('id,name,position,color').order('position')]);if(total.error||contacts.error||deals.error||stages.error)throw total.error??contacts.error??deals.error??stages.error;const cs=(contacts.data??[]) as ContactRow[],ds=(deals.data??[]) as DealRow[],ss=(stages.data??[]) as StageRow[],won=ds.filter(d=>d.status==='won'),lost=ds.filter(d=>d.status==='lost'),closed=won.length+lost.length;const days=new Map<string,number>();for(const c of cs){const key=new Date(c.created_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});days.set(key,(days.get(key)??0)+1);}setReport({totalContacts:total.count??0,newContacts:cs.length,open:ds.filter(d=>d.status==='open').length,won:won.length,lost:lost.length,pipelineValue:ds.filter(d=>d.status==='open').reduce((s,d)=>s+Number(d.value??0),0),conversion:closed?won.length/closed:0,average:won.length?won.reduce((s,d)=>s+Number(d.value??0),0)/won.length:0,contactsByDay:[...days].map(([label,value])=>({label,value})),stages:ss.map(stage=>{const rows=ds.filter(d=>d.stage_id===stage.id);return{name:stage.name,count:rows.length,value:rows.reduce((s,d)=>s+Number(d.value??0),0),color:stage.color};})});}catch(e){const n=normalizeError(e);console.error('[reports]',{message:n.message,code:n.code});setError('Não foi possível carregar os relatórios.');}finally{setLoading(false);}},[accountId,period]);
useEffect(()=>{if(profileLoading)return;if(!accountId){setLoading(false);setError('Não foi possível carregar os relatórios.');return;}void load();},[profileLoading,accountId,load]);
const maxContacts=useMemo(()=>Math.max(1,...(report?.contactsByDay.map(i=>i.value)??[1])),[report]);const maxStage=useMemo(()=>Math.max(1,...(report?.stages.map(i=>i.count)??[1])),[report]);
const cards=report?[['Total de contatos',report.totalContacts,Users],['Novos no período',report.newContacts,ContactRound],['Oportunidades abertas',report.open,BriefcaseBusiness],['Valor em negociação',formatCurrency(report.pipelineValue,defaultCurrency),CircleDollarSign],['Negócios ganhos',report.won,Trophy],['Negócios perdidos',report.lost,TrendingDown],['Taxa de conversão',percent.format(report.conversion),Target],['Ticket médio',formatCurrency(report.average,defaultCurrency),BarChart3]] as const:[];
return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Desempenho comercial</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Relatórios</h1><p className="mt-1 text-muted-foreground">Acompanhe o desempenho comercial da sua empresa.</p></div><div className="w-full sm:w-52"><label className="mb-1.5 block text-xs font-medium text-muted-foreground" htmlFor="report-period">Período</label><Select value={period} onValueChange={v=>setPeriod(v as Period)}><SelectTrigger id="report-period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">Últimos 7 dias</SelectItem><SelectItem value="30">Últimos 30 dias</SelectItem><SelectItem value="month">Este mês</SelectItem><SelectItem value="90">Últimos 3 meses</SelectItem></SelectContent></Select></div></div>
{error?<div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5"><p>{error}</p><Button className="mt-3" variant="outline" onClick={()=>void load()}>Tentar novamente</Button></div>:null}{loading?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><SkeletonCard key={i}/>)}</div>:null}
{!loading&&!error&&report?<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,Icon])=><Card key={title} className="overflow-hidden"><CardHeader className="flex-row items-center justify-between pb-2"><CardTitle className="text-sm text-muted-foreground">{title}</CardTitle><span className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="size-4"/></span></CardHeader><CardContent><p className="text-2xl font-bold">{value}</p></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Evolução de contatos</CardTitle></CardHeader><CardContent>{report.contactsByDay.length?<div className="flex h-64 items-end gap-2 overflow-x-auto pb-6" aria-label="Novos contatos por dia">{report.contactsByDay.map(item=><div key={item.label} className="flex min-w-10 flex-1 flex-col items-center gap-2" title={`${item.label}: ${item.value}`}><span className="text-xs font-semibold">{item.value}</span><div className="w-full rounded-t-md bg-primary/80" style={{height:`${Math.max(8,item.value/maxContacts*180)}px`}}/><span className="text-[10px] text-muted-foreground">{item.label}</span></div>)}</div>:<EmptyChart/>}</CardContent></Card><Card><CardHeader><CardTitle>Contatos por etapa</CardTitle></CardHeader><CardContent>{report.stages.some(s=>s.count)?<div className="space-y-4">{report.stages.map(stage=><div key={stage.name}><div className="mb-1 flex justify-between text-sm"><span>{stage.name}</span><span className="text-muted-foreground">{stage.count} · {formatCurrency(stage.value,defaultCurrency)}</span></div><div className="h-2 rounded-full bg-muted"><div className="h-full rounded-full" title={`${stage.name}: ${stage.count}`} style={{width:`${stage.count/maxStage*100}%`,backgroundColor:stage.color}}/></div></div>)}</div>:<EmptyChart/>}</CardContent></Card></div></>:null}</div>}
function EmptyChart(){return <div className="grid h-56 place-items-center rounded-xl border border-dashed text-center text-sm text-muted-foreground">Ainda não há dados suficientes para este relatório.</div>}

